//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTrainer
    {
        public int id { get; set; }
        public int Weight { get; set; }
        public int Height { get; set; }
        public int BarbellSquat { get; set; }
        public int Deadlift { get; set; }
        public int BenchPress { get; set; }
        public int Pullups { get; set; }
        public string BodyType { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
