//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExercisesForClient
    {
        public Nullable<int> Id_client { get; set; }
        public string First_Day { get; set; }
        public string Second_Day { get; set; }
        public string Third_Day { get; set; }
        public int Number { get; set; }
    
        public virtual DataClient DataClient { get; set; }
    }
}
