//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public string messages1 { get; set; }
        public int id_Message { get; set; }
        public int Who_sender { get; set; }
        public int Who_recipient { get; set; }
        public Nullable<int> GroupMessage { get; set; }
        public System.DateTime Date { get; set; }
    }
}
