//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultExercises
    {
        public int number { get; set; }
        public string First_Day { get; set; }
        public string First_Day_Weight { get; set; }
        public string First_Day_Quantity { get; set; }
        public string Second_Day { get; set; }
        public string Second_Day_Weight { get; set; }
        public string Second_Day_Quantity { get; set; }
        public string Third_Day { get; set; }
        public string Third_Day_Weight { get; set; }
        public string Third_Day_Quantity { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual DataClient DataClient { get; set; }
    }
}
